config_version: 1

game:
  max_turns: 36
  major_event_interval: 3
  micro_event_prob: 0.20
  starting:
    mau: 10000
    latency_ms: 280
    security: 40
    cash: 500
    burn_monthly: 50
    ec2_count: 1
    action_cap: 1

growth:
  base_mau_rate: 0.02
  latency_floor: 120
  latency_ceiling: 800
  security_decay_per_turn: 1

cost:
  ec2_monthly: 50
  alb_monthly: 20
  rds_monthly: 60
  rds_multi_az_extra: 60
  elasticache_monthly: 80
  cloudfront_monthly: 25
  waf_monthly: 15
  net_private_nat_monthly: 30
  autoscaling_base: 10
  obs_monthly: 12
  graviton_discount: 0.20
  ri_discount: 0.20

performance:
  alb_bonus_ms: -30
  rds_bonus_ms: -15
  rds_multi_az_bonus_ms: -10
  elasticache_bonus_ms: -70
  cloudfront_bonus_ms: -40
  autoscaling_stability_ms: -25
  ec2_add_bonus_ms: -20
  ec2_remove_penalty_ms: 30
  base_rps_per_ec2: 100

security_bonus:
  rds_bonus: 5
  waf_bonus: 15
  net_private_nat_bonus: 8
  obs_bonus: 12
  multi_az_bonus: 12

sla:
  warn_latency_ms: 300
  fail_latency_ms: 350
  fail_streak_required: 3

bankruptcy_grace_turns: 2

event_security_thresholds:
  audit_warn: 50
  audit_fail: 60